### ISSUE TITLE
1.8 pipes fail to load on 1.8.8

### ISSUE THREAD

**Issue by AlexIIL** [AlexIIL/Buildcraft_1.8_Issues#103]
with something like

```
null was not an instanceof ItemPipe!buildcraft|transport:item.buildcraftPipe.pipefluidscobblestone
Pipe failed to load from NBT at BlockPos{x=-704, y=31, z=378}
```

**Comment by AlexIIL** [comment]
in 1.8 `buildcraft|transport:item.buildcraftPipe.pipefluidscobblestone`
but in 1.8.9 `buildcraft|transport:buildcraftPipe.pipefluidscobblestone`
(no `item.`)

**Comment by AlexIIL** [comment]
@maqjav Could you try with this jar? https://www.dropbox.com/s/jvft1vp3c0ny6x9/buildcraft-7.2.0-pre8-migration-ver1.jar?dl=1

**Comment by maqjav** [comment]
I tried loading my 0.10-alpha world with 7.2.0-pre8-migration-ver1 but same... I see a lot of exceptions in the log, I don't know if they are related:
https://gist.github.com/maqjav/e0685f134e32964e7c1e

I noticed that there is only 1 item that loads properly (just in case it adds some light). I have a couple of redstone engines in a chest and they are loading properly. However the rest of items in chests/inventory or in my world are gone (including redstone engines that are in my world).

**Comment by AlexIIL** [comment]
Could you try running 0.12-alpha-migration (1.8) and then load the world with 7.2.0-pre8-migration-ver1 (1.8.9)? (I know it's annoying, but for now you will need to walk around your world a bit to make sure you load everything with 0.12 and then load everything with pre8).

I'm not sure why all the other blocks are vanishing though, but I hope this sorts out the pipe issue.

**Comment by maqjav** [comment]
Same results as 0.10->pre8-migration-ver1: https://gist.github.com/maqjav/d06125c6faa0e850a1ca
With 0.12-alpha-migration everything works fine (I guess you knew that already :P)

**Comment by AlexIIL** [comment]
It's very slightly different... In the other log files there were a lot of "null pipe at (1,2,3)", but none in this log file... I'll stop giving you test jars and try it out myself...

**Comment by maqjav** [comment]
I don't mind helping, as you prefere :)
And you are right, the null traces are gone.

**Comment by AlexIIL** [comment]
It's just much quicker for me to do it, as I think there will be a lot of trial end error. One thing that would help though is could I have your world? It's just helpful to have a test world that's got proper structures inside of it, rather than having to build up a full one myself :)

**Comment by maqjav** [comment]
Here you have it! https://www.dropbox.com/s/k6eg1bm3asf026t/my_world_0.12.rar?dl=0
I loaded it without other mods, so you don't have extra errors loading it. 
When you will download it let me know so I remove the link.

Oh, and don't mess up with my church! ;)

**Comment by AlexIIL** [comment]
Thanks, I have it :)

**Comment by maqjav** [comment]
Deleted :)

**Comment by AlexIIL** [comment]
Can I just quickly verify: did you make this? (I'm talking about the iron kinesis pipes)
![screenshot from 2016-01-27 12 56 25](https://cloud.githubusercontent.com/assets/3751138/12614054/6f8e74f0-c4f5-11e5-89f3-aa73ab88ab4b.png)

**Comment by AlexIIL** [comment]
And is this setup meant to be connected to a power pipe or not? (I'm wondering if something horrible has happened with mods which means that it didn't transfer properly)
![screenshot from 2016-01-27 12 58 34](https://cloud.githubusercontent.com/assets/3751138/12614120/d04128a6-c4f5-11e5-999a-fbc7f01ef40e.png)

**Comment by AlexIIL** [comment]
Ignoring the potential BC pipes not transferring, WOW that is an impressive church!

**Comment by maqjav** [comment]
Yep, I made all that mess.

The pipes you find there are a little bit messy because I was testing different setups the last time I played (just to forze bugs). If you construct something with the assembly table that is underneath you will see that the energy is transfered between the engine and the 2 lasers. Right now the assembly table doesn't have enough materials to construct something, that's why you don't see the energy (intended?). If you do so, you will see that the T connetion between the lasers and the engine shows energy only in one of the sides, both lasers work, but only 1 receive energy (I don't know if this is fixed in the last pre).

The little chest+stirling engine system in the left side provides energy to the lasers whenever the combustion engine runs out of lava. However it was a poor design and a bad setup with the gates so I lost every item that I wanted to burn in the engine xD

The pipe full of lava is connected to a pump further away.

There are some chests under the church (main gate) where I have some materials, pipes, etc. Just in case you need to construct something else.

**Comment by AlexIIL** [comment]
So they are meant to be iron pipes then. That's good, as otherwise that would mean very bad stuff for the world :D

I won't resend you the world unless I can't program something to special case load up the world for you. Essentially I'm going to be doing some questionable hard-coding to make sure I can make a jar file that will fully port the world over (which is why its a separate version, with -migration-ver# at the end).

**Comment by maqjav** [comment]
Thanks for your time and effort :)
I wish I would know how to do this stuff, I still don't understand how minecraft works inside.

**Comment by AlexIIL** [comment]
This looks better...
![screenshot from 2016-01-27 15 13 30](https://cloud.githubusercontent.com/assets/3751138/12617664/95e4aa26-c508-11e5-98c2-e283fff58469.png)

**Comment by maqjav** [comment]
Yay! you got pipes and I see there a gate?
Awesome :)

**Comment by AlexIIL** [comment]
Basically what's happening is that all blocks have vanished, but all TileEntities are still loading and immediately being destroyed because they don't have a block to be paired with. However I can force-set the block where the tile entity is to the block the tile entity needs. Essentially, all of the gates and wires loading is a side effect, because all of that data is still there.

**Comment by maqjav** [comment]
Aha... and why don't they have a block to be paired with? have the entities changed in 1.8.9 or it works completely in a different way?

**Comment by AlexIIL** [comment]
Sort of... basically all blocks are stored in a "registry" of the string name of a block (say "BuildCraftTransport:genericPipeBlock" to an integer ID (say 631). Then all blocks are actually stored in a dense 3 dimensional "array" of these integers, so 0 for air and 631 for pipes. What has happened is that this registry hasn't made it over from 1.8 forge (when there were some massive registry issues) into 1.8.9, which caused all unknown ids (in this case 631 for pipes) to be reset to 0 (air). However the tile entities are stored separately, so they were not affected by this bug and can be used to reset the block BACK to whatever NEW id is used by pipes (say 786).

**Comment by AlexIIL** [comment]
Also, I'm having to ignore a lot of normal checks to force this to make PERFECTLY sure that the world can be migrated (so dupe bugs might exist, or you might not be able to break blocks...), so change to a non-migration version of 7.2.0 after you have loaded it with a migration version.

**Comment by maqjav** [comment]
Interesting... so then you have to do it with every single Bc block.. that sounds painfull. Perhaps a world with more stuff would be more useful, I didn't have many BC things in mine.

**Comment by AlexIIL** [comment]
Its fine, Its not _too_ hard to do (because of the way BC has a generic "BuildCraft Tile Entity" that all others extend from, the loading behaviour is done inside of that to make it simpler. The main issue is that some of the items don't seem to have migrated over properly (I've only noticed pipes though, the wrench, a tank, a marker and pipe sealant seem to have made it across)

**Comment by maqjav** [comment]
I have a copy of my world with alpha 10, just in case you need it.

**Comment by AlexIIL** [comment]
Was the world you sent me alpha 10 or the migration alpha for 1.8?

**Comment by maqjav** [comment]
The world I sent you was the migration alpha for 1.8 (buildcraft-0.12-alpha-migration.jar)

**Comment by AlexIIL** [comment]
ok. I don't think it will make much difference, but you will need to run a new migration version for 1.8 and 1.8.9 to make them work fully.

**Comment by maqjav** [comment]
That's ok!, after all this work that's the least of the problems

**Comment by AlexIIL** [comment]
It does mean that you will need to walk all around your world, once in 0.13-alpha-migration, and once in 7.2.0-pre8-migration-ver2 to make sure that ALL BC tile entities are transfered.

**Comment by AlexIIL** [comment]
(And yes those are future versions for migration)

**Comment by AlexIIL** [comment]
Much better!
![screenshot from 2016-01-27 17 38 40](https://cloud.githubusercontent.com/assets/3751138/12622360/d2e323a8-c51c-11e5-8c5a-c412eb26e333.png)

**Comment by maqjav** [comment]
Yes! now you got every single thing! even the assembly table now has textures!

**Comment by AlexIIL** [comment]
*except the redstone engines you can't see :P

But they should load in the next version, so it should be fine.

**Comment by maqjav** [comment]
What about the pump, and the wires, chips and other electronic devices?. If I'm not wrong there should be some inside the chest beside the assembly table.

**Comment by AlexIIL** [comment]
This is the assembly chest:
![screenshot from 2016-01-27 17 51 39](https://cloud.githubusercontent.com/assets/3751138/12622733/a41cb01e-c51e-11e5-9be1-2a1a5fd0e63b.png)

**Comment by AlexIIL** [comment]
Lowest double-chest in the bit below the church:
![screenshot from 2016-01-27 17 53 19](https://cloud.githubusercontent.com/assets/3751138/12622783/e75e3f00-c51e-11e5-9041-5e17c08d634c.png)

**Comment by AlexIIL** [comment]
I know there used to be pipes in that chest and to get them into 1.8.9 you will need to place all of them in the world. Which is annoying, but at least you don't have 7 stacks of pipes to place.

**Comment by maqjav** [comment]
I was just wondering about those pipes. Its ok, I will place them somewhere.

**Comment by AlexIIL** [comment]
Ok, I'm preparing the jars for you to use now- if they work, I'll create a forum thread about it.

**Comment by AEnterprise** [comment]
@AlexIIL maybe it might be an idea to make that first version chunkload all chunks that already exist on the server one by one for a few ticks? that might be an easier solution for people then having to run around all chunks the world

**Comment by AlexIIL** [comment]
...That... would make a lot of sense actually. Except that there could be a lot of chunks to load and I have no idea which chunks actually exist on disk

**Comment by AEnterprise** [comment]
i duno exactly how to check for existing chunks, there must be a way as vanilla does it somehow to only gen chunks that don't exist yet, i also sugest loading them in batches of 10-20 at a time, with a progress indication to player so they know it's still going (as it could take a bit on large worlds) and when it's done

**Comment by AlexIIL** [comment]
When MC needs to load a chunk it will first ask the loader if a SPECIFIC chunk exists on disk, and if it doesn't it generates it. The issue I have is that I need to check all existing chunks (so I would need to scan the disk manually. Its technically possible, but as I am already hacking around to make blocks and items load I don't know what doesn't work properly, so I would rather people know that this is a buggy-as-f**\* process, and have them check their builds manually (they know what it was meant to look like, but BC doesn't) so automating it wouldn't actually help in this case.

**Comment by maqjav** [comment]
I'll be back at home in 1 hour, so I will test it then.
Just to clarify.I will have to use the new 1.8 JAR, place every single pipe on my world, walk arround so it loads every BC item and then move to the 1.8.9-migration-whatever, right?

**Comment by AlexIIL** [comment]
These are the formal instructions:
1. Backup your world folder to a separate folder. **This is REALLY important in case something goes wrong**
2. Load up your world in alpha 12 (migration version, jar 1)
3. Place all pipes you have in chests in the world
4. Load up ALL areas of the world that you have build-craft tiles in. It might help to do this in singleplayer with your render distance set to 32 so you load up the maximum number of chunks possible. (you will probably want to lower all other graphical settings though.)
5. Save the world, and back it up again (so you can restart from here if the NEXT step fails)
6. Load the world in pre8-migration-ver2 (jar 2), again walking around the ENTIRE world to make sure that all buildcraft tiles are loaded.
7. Load up the world in pre9 (the next version of buildcraft).
8. Check ALL your builds to make sure they all survived through to 1.8.9.
9. Report any failed blocks to the forum (INSERT LINK HERE)

The first jar you will need: https://www.dropbox.com/s/p22ctszue8fyhfv/buildcraft-0.12-alpha-migration.jar?dl=1

The second jar you will need: https://www.dropbox.com/s/sb4ptgn0h69h6rk/buildcraft-7.2.0-pre8-migration-ver2.jar?dl=1

**Comment by maqjav** [comment]
Ok... it's doing something weird.

I did all the process and when I started the game with 7.2.0-pre8-migration-ver2 I could see every pipe I had in my chests and placed around, however the most of the pipes I had in my world they were invisible (I say invisible because I could walk on top of them). After closing and opening the game several times more and more pipes where rendering in every startup (but onlly pipes).
The quarry, engines, pumps, lasers, assembly table... they arent here.

I can see in my inventory some tanks, redstone engines and sealant.

I started with a game saved with 0.10-alpha -> 0.12-alpha-migration-version -> 7.2.0-pre8-migration-ver2.

I'm going to try again waiting more time around the engines, maybe it didn't record them properly?

**Comment by AlexIIL** [comment]
There's currently a bug in 1.8.9 BC that makes pipes not appear until you place a block down next to them, does that changed anything? Also, is there a lot of log spam?

**Comment by AlexIIL** [comment]
The "no quarry, engines, pumps, lasers, assembly table" isn't meant to happen, and if you can't collide with the blocks then that's not good at all...

**Comment by maqjav** [comment]
Here you can see the last log (I tried the whole process but same result), only my pipes and some stuff in my chests are ported: https://gist.github.com/maqjav/cd83378269a16055faad

**Comment by maqjav** [comment]
Oh the electronic devices I had in my chest are here too (wires, chipsets, etc)

**Comment by AlexIIL** [comment]
I'll retest it and try to figure out what's going on...

**Comment by AlexIIL** [comment]
When I try it works (even the wooden engines migrate). I'll try rebuilding a jar file, and at worst, sending you the world.

**Comment by maqjav** [comment]
The 0.12 version JAR is the same one you sent me yesterday?

**Comment by AlexIIL** [comment]
A 0.13 version, sorry. I'll upload the 0.13 version: https://www.dropbox.com/s/nuc92vn2x90azeb/buildcraft-0.13-alpha-migration.jar?dl=1

**Comment by AlexIIL** [comment]
However I can't really see how it would make a difference as 0.13 didn't add a lot of stuff. Another question, did you BC anywhere other than your church?

**Comment by maqjav** [comment]
Just around the church, so I dont have to walk too much.

**Comment by AlexIIL** [comment]
That's helpful- I had just discovered your train tunnel and was worried that a lot more walking was needed than I thought.

**Comment by maqjav** [comment]
I was asking you before about the 0.12 version because the world I sent you was created with 0.12, however today I'm trying to load a 0.10 world with the new 0.12 version you sent me today. If it's the same version as yesterday then it's ok, if it's different... maybe that's why it isn't working.

**Comment by AlexIIL** [comment]
Theoretically It shouldn't make a difference, so I've been using the world you sent me and loading it with 0.13 and then 7.2.0-pre8-migration-ver2

**Comment by maqjav** [comment]
Nothing.. it doesn't want to work... I tried using the world I sent you with 0.13 and then 7.2.0-pre8-migration-ver2 (nothing). I also tried without mods with 1.8.9 (I had a couple of them installed) but same result... I can see only the pipes...

Ideas? why might it be working in your computer and not here?
What version of forge are you using with both versions? just in case mine are different and maybe they are affecting somehow.

**Comment by AlexIIL** [comment]
My 0.13 forge is 11.15.0.1608, and my pre8-migration is 11.15.0.1718

**Comment by AlexIIL** [comment]
However I didn't have any mods in 1.8 or 1.8.9 so that _may_ be something todo with it.

**Comment by AlexIIL** [comment]
... And I've just realised how I can migrate pipes as items. Thats nice :)

**Comment by maqjav** [comment]
I'm going to try with your versions, I'm using 1.8-11.14.4.1577 and 1.8.9-11.15.0.1723, perhaps my 1.8 version is too old.

**Comment by maqjav** [comment]
Wait a second, are you loading your 1.8 world with a 1.8.8  forge? I see that the version 11.15.0.1608 is for 1.8.8, and not 1.8

**Comment by AlexIIL** [comment]
Sorry, the first forge version was for 1.8 (11.15.0.1608) and my second forge version was for 1.8.9 (11.50.0.1718). 7.2.0-pre-8-migration is the 1.8.9 version, 0.13-alpha is the 1.8 version. Sorry for the confusion.

**Comment by AlexIIL** [comment]
Also I've just managed to get pipes as items loading so I'll have a new pre8-migration-ver3 soon :)

**Comment by AlexIIL** [comment]
(Which means you no longer need to place every single pipe in chest down)

**Comment by maqjav** [comment]
Oh, that's great then, it was the painfull part of this process :)
Did you find out why the rest of items weren't ported?

**Comment by AlexIIL** [comment]
I haven't been able to reproduce any items other than pipes not migrating, so no :/

**Comment by maqjav** [comment]
And are you sure you are using 1.8-11.15.0.1608 for 0.13? I'm checking the forge files page and I don't see that version for 1.8, the latest for 1.8 is 11.14.4.1577 :) I want to try exactly with the same versions that you are using just in case it is related.

**Comment by AlexIIL** [comment]
Anyway, can you try loading up your world (in 1.8) with this version? (https://www.dropbox.com/s/24feujbpfik6z8h/buildcraft-0.14-alpha-migration.jar?dl=1) and then loading it up (in 1.8.9) with this version? (https://www.dropbox.com/s/9idh2tt02d9c9dq/buildcraft-7.2.0-pre8-migration-ver3.jar?dl=1)

**Comment by AlexIIL** [comment]
Sorry, ignore the above until I reply to your last forge question....

**Comment by maqjav** [comment]
Don't worry! ;)

**Comment by AlexIIL** [comment]
Oh! I read the wrong value from build build.gradle :P
11.14.4.1577 is the ACTUAL version of forge 1.8 was using
(my build text file looks like this:)

``` java
    //1.8.8
    // version = "1.8.8-11.15.0.1608-1.8.8"
    // 1.8
    version = "1.8-11.14.4.1577"
```

(This is from my 1.8 build environment)

**Comment by maqjav** [comment]
Hehehe, it's alright! then we are using the same version.
I will try to load the 1.8.9 with your version,and test the last JARs.

**Comment by AlexIIL** [comment]
If any of the pipes don't visibly exist but you can stand on them then its a bug in pre-8 that has been fixed for pre-10. If any machines don't exist after you have loaded it up then that’s a separate problem...

**Comment by AlexIIL** [comment]
One other difference between my environment and yours is other mods- I have been using just BC with no additional mods installed. I don't know if that makes a difference or not.

**Comment by maqjav** [comment]
Good news! it works!

All my world is ported including my items in the chests (pipes, engines, etc)

I used your last JARs with 1.8-11.14.4.1577 (0.14) and 1.8.9-11.50.0.1718 (7.2.0-pre8-migration)
I loaded without mods (although I tried yesterday without them and it didn't load properly).

I'm going to repeat the whole process with the new JARs and my old version of forge.

Good job!

**Comment by AlexIIL** [comment]
Great :)

**Comment by maqjav** [comment]
It loads great with the old version for forge 1.8.9, it seems that you fixed whatever the issue was in the last release! you are a genius ;)

Now I will be able to continue testing BC and constructing the cathedral.

Thank you very much.

**Comment by AlexIIL** [comment]
Make sure you upgarde to pre9 first though, pre8-migration is stupidly unstable and  log-spammy :)

**Comment by maqjav** [comment]
I see that the most of textures are fixed (I only see a few missing). I'm going to upgrade to that version ;) I see you have been very busy.

**Comment by AlexIIL** [comment]
Not really- you missed about a months worth of releases as I have left the migration version for a long time. Also I've been finding less and less actual bugs so getting all of the models+textures done to release it properly (officially on curse and the BC website)

**Comment by maqjav** [comment]
Now I have to check all the new improvements.

It works fine with pre9, althought I'm seeing the bug you were talking about invisible pipes, they are there but I don't see them (some of them). We'll be waiting for pre10 to fix this.

Great job ;) I will follow you (and the rest of the BC team) at the forum.

**Comment by AlexIIL** [comment]
You can place a block next to an invisible pipe to force it to update. Its annoying if you have a lot of pipes, but its a temp fix for when you are relatively close to it.

**Comment by AlexIIL** [comment]
(Closing this as I assume its fixed)

**Comment by AlexIIL** [comment]
I've just noticed that markers don't keep over in chests. dammit.

**Comment by maqjav** [comment]
I didn't realize about that :S

**Comment by AlexIIL** [comment]
Fortunately you don't have a shortage of resources to make new ones :P
