### ISSUE TITLE
Blueprint Viewing crash

### ISSUE THREAD

**Issue by LuigiHutch** [AlexIIL/Buildcraft_1.8_Issues#68]
Buildcraft 7.2.0 Prerelease 1

Blueprint Viewing crash: https://gist.github.com/LuigiHutch/19d94dcc52e4d217fe44 

Image of blueprint:  ![2015-12-18_00 21 24](https://cloud.githubusercontent.com/assets/9326429/11886054/6f67cad2-a51d-11e5-9e76-d56d8553ae0c.png)

Aftermath of crash (Pipes Invisible): ![2015-12-18_00 24 14](https://cloud.githubusercontent.com/assets/9326429/11886068/b2b55250-a51d-11e5-80ed-1a9990a9d0e7.png)

Personal Notes about the blueprint viewer:
- It is very difficult to actually view the blueprint and control the angle of where you are viewing it from

Thanks
-LuigiHutch

**Comment by AlexIIL** [comment]
I think the invisible pipe thing is unrelated as it has cropped up elsewhere in test worlds before, but I don't know exactly where the bug is

**Comment by AlexIIL** [comment]
Also I need to have another look at how the blueprint viewer works as it was a quick impl to test something.

**Comment by AlexIIL** [comment]
Ok after looking into it can you narrow down which block is causing the bug?

**Comment by AlexIIL** [comment]
(The problem is not with the renderer but with a specific block not returning the models it should)

**Comment by AlexIIL** [comment]
I think that has been fixed for all buildcraft based models now

**Comment by LuigiHutch** [comment]
Same Build still crashes with BC 7.2.0 Pre 6. Slightly Different crashlog though:
https://gist.github.com/LuigiHutch/8576aea3370e80af2b7f

**Comment by AlexIIL** [comment]
[Past me]: "Oh I know, lets throw an exception whenever I use a model in a way it was never meant to be used"

(Its fixed in my dev and pre7 will stop throwing that exception)

**Comment by LuigiHutch** [comment]
Fixed :D
